### PR TITLE
--stop: Handle fwrite() failure

### LINKED ISSUE #2: Output file silently truncated when not enough space is available
Thank you very much for this tool (and your work on `-ftime-trace`)!

I tested it on our medium-sized project, where `--stop` creates a 3.8GB output file. I did not have enough free space in the output folder (as I later realized). However, the `--stop` command succeeded (exit code 0) and did not give an error message. Only when `--analyze` failed to parse the JSON file I realized the output had been truncated.

Other file writing errors are detected, such as missing write permissions.

### PR DESCRIPTION
**Pull request by jspam**
This handles the case where the file could be opened, but not completely
written to, e.g. if there is not enough space on the device.

Closes #2.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -228,7 +228,14 @@ static int RunStop(int argc, const char* argv[])
         printf("%sERROR: failed to write result file '%s'.%s\n", col::kRed, outFile.c_str(), col::kReset);
         return 1;
     }
-    fwrite(bigJson.data(), 1, bigJson.size(), fout);
+    const size_t numBytesWritten = fwrite(bigJson.data(), 1, bigJson.size(), fout);
+    if (numBytesWritten != bigJson.size())
+    {
+        printf("%sERROR: failed to write result file '%s', %llu of %llu bytes written.%s\n",
```
Comment (aras-p) [inline src/main.cpp:234]: Minor: I think `%zu` is a widely working format arg for `size_t` types, without need for extra casts.

**Review by aras-p — APPROVED** [review]
Sweet, thanks!
